AllCops:
  TargetRubyVersion: 3.3
  NewCops: disable
  SuggestExtensions: false
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
    - 'test/dummy/bin/**/*'
    - 'gemfiles/**/*'

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets

Style/RedundantBegin:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
