name: "Auto Author Assign"
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  issues: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@bdd7688cbf9e6d5683f02f8c7d8ae4062a254b6d # v3.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
